### ISSUE TITLE
(docs) Does the unencrypted port for the dryer require the PSK, too?

### ISSUE THREAD

**Issue by CRTified** [osresearch/hcpy#1]
Hi, thank you for your effort. Does the dryer require the PSK, too?

I tried applying your code on an `EQ.9 plus connect s500` coffee maker, and first scanned where to connect:
```
$ sudo nmap -sS 192.168.XX.XX
Starting Nmap 7.92 ( https://nmap.org ) at 2022-02-01 09:43 CET
Nmap scan report for 192.168.XX.XX
Host is up (0.099s latency).
Not shown: 999 closed tcp ports (reset)
PORT   STATE SERVICE
80/tcp open  http
MAC Address: 68:A4:0E:XX:XX:XX (BSH Hausgerte GmbH)

Nmap done: 1 IP address (1 host up) scanned in 40.94 seconds
```

As you mentioned that the connection was unencrypted, I assumed that no PSK is needed, but dropping the SSL socket from your code yields the following result:
```
--- request header ---
GET /homeconnect HTTP/1.1
Upgrade: websocket
Host: 192.168.XX.XX
Origin: 
Sec-WebSocket-Key: qnpSjK5rTYFwtZSS8Y1eIg==
Sec-WebSocket-Version: 13
Connection: Upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: lpgdCwDkx9WcT3UBrMEJmotBgHg=
-----------------------
++Rcv raw: b'\x82~\x00\x90b\xc1B\xcfMe\xcf\xe6a\xfa\x19#\xff;\xb0\xc04\x9e\xd7\xeb&\xb3\xed\x91F\xb0\xf8\xc9G\x08\xd9\xc0\xfabj\x18l\xe8\x1fQ\x15\xf8 f\x16\xf5\xd3\xe3\x8dx\xe85A\xb1|2\x024\xfcS\x18>\xf1\xdb|U~\x92\x0e\xa2n\xc0\xcb\x05\xbc\x89\x92\x17`\xf6Z5\x03!\xcd\xe8"\'\xf1n"\xf4i,\x1d,\x80=\x1a\x94z-\xc0x\xa5\x01\x8c:\xec\x94\x94\x03r5\xa7\x94\x90=,N\xec\tqK\x1d=\xe2M\x9e$\xb5\x90O\xaa\xf3\xa5\x00T\xab\x04~\x88\x06\xdf'
++Rcv decoded: fin=1 opcode=2 data=b'b\xc1B\xcfMe\xcf\xe6a\xfa\x19#\xff;\xb0\xc04\x9e\xd7\xeb&\xb3\xed\x91F\xb0\xf8\xc9G\x08\xd9\xc0\xfabj\x18l\xe8\x1fQ\x15\xf8 f\x16\xf5\xd3\xe3\x8dx\xe85A\xb1|2\x024\xfcS\x18>\xf1\xdb|U~\x92\x0e\xa2n\xc0\xcb\x05\xbc\x89\x92\x17`\xf6Z5\x03!\xcd\xe8"\'\xf1n"\xf4i,\x1d,\x80=\x1a\x94z-\xc0x\xa5\x01\x8c:\xec\x94\x94\x03r5\xa7\x94\x90=,N\xec\tqK\x1d=\xe2M\x9e$\xb5\x90O\xaa\xf3\xa5\x00T\xab\x04~\x88\x06\xdf'
error handling msg 'utf-8' codec can't decode byte 0xc1 in position 1: invalid start byte b'b\xc1B\xcfMe\xcf\xe6a\xfa\x19#\xff;\xb0\xc04\x9e\xd7\xeb&\xb3\xed\x91F\xb0\xf8\xc9G\x08\xd9\xc0\xfabj\x18l\xe8\x1fQ\x15\xf8 f\x16\xf5\xd3\xe3\x8dx\xe85A\xb1|2\x024\xfcS\x18>\xf1\xdb|U~\x92\x0e\xa2n\xc0\xcb\x05\xbc\x89\x92\x17`\xf6Z5\x03!\xcd\xe8"\'\xf1n"\xf4i,\x1d,\x80=\x1a\x94z-\xc0x\xa5\x01\x8c:\xec\x94\x94\x03r5\xa7\x94\x90=,N\xec\tqK\x1d=\xe2M\x9e$\xb5\x90O\xaa\xf3\xa5\x00T\xab\x04~\x88\x06\xdf'
++Rcv raw: b'\x88\t\x03\xeaTimeout'
++Rcv decoded: fin=1 opcode=8 data=b'\x03\xeaTimeout'
++Sent raw: b'\x88\x82jx\xd6mi\x90'
++Sent decoded: fin=1 opcode=8 data=b'\x03\xe8'
Traceback (most recent call last):
  File "/home/richard/hcpy/hcpy", line 155, in <module>
    buf = ws.recv()
  File "/nix/store/k0qjfvyrw4h8v3g3lji039fq9mjffjq5-python3.9-websocket-client-1.2.1/lib/python3.9/site-packages/websocket/_core.py", line 354, in recv
    opcode, data = self.recv_data()
  File "/nix/store/k0qjfvyrw4h8v3g3lji039fq9mjffjq5-python3.9-websocket-client-1.2.1/lib/python3.9/site-packages/websocket/_core.py", line 377, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/nix/store/k0qjfvyrw4h8v3g3lji039fq9mjffjq5-python3.9-websocket-client-1.2.1/lib/python3.9/site-packages/websocket/_core.py", line 396, in recv_data_frame
    frame = self.recv_frame()
  File "/nix/store/k0qjfvyrw4h8v3g3lji039fq9mjffjq5-python3.9-websocket-client-1.2.1/lib/python3.9/site-packages/websocket/_core.py", line 435, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/nix/store/k0qjfvyrw4h8v3g3lji039fq9mjffjq5-python3.9-websocket-client-1.2.1/lib/python3.9/site-packages/websocket/_abnf.py", line 337, in recv_frame
    self.recv_header()
  File "/nix/store/k0qjfvyrw4h8v3g3lji039fq9mjffjq5-python3.9-websocket-client-1.2.1/lib/python3.9/site-packages/websocket/_abnf.py", line 293, in recv_header
    header = self.recv_strict(2)
  File "/nix/store/k0qjfvyrw4h8v3g3lji039fq9mjffjq5-python3.9-websocket-client-1.2.1/lib/python3.9/site-packages/websocket/_abnf.py", line 372, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/nix/store/k0qjfvyrw4h8v3g3lji039fq9mjffjq5-python3.9-websocket-client-1.2.1/lib/python3.9/site-packages/websocket/_core.py", line 519, in _recv
    return recv(self.sock, bufsize)
  File "/nix/store/k0qjfvyrw4h8v3g3lji039fq9mjffjq5-python3.9-websocket-client-1.2.1/lib/python3.9/site-packages/websocket/_socket.py", line 125, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.
```

It looks a lot like the PSK *is* needed. Would be great if you could clarify this :)
I might also be able to help with support for the mentioned coffee maker, so feel free to ping me if you want (just didn't have time to get the PSK right now).

**Comment by osresearch** [comment]
Thanks for testing it on your machine!  My initial focus was on the the dishwasher and I had ignored the other appliance since it seemed to be clear text at first, although I'm seeing the same traffic as you -- the connection is made over the port 80, but the data appears to be encrypted.

```
--- response header ---
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: 2doMc2qCMmlZszJY1AR1IqR4ml0=
-----------------------
++Rcv raw: b'\x82~\x00\xa0\xbb....
++Rcv decoded: fin=1 opcode=2 data=b'\xbb>\xee\x04f...
error handling msg 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte 
```

`HomeApplianceLibraryCommunicator.initHomeAppliance()`'s last argument is a large string sent that includes the PSK for the dishwasher and what might be an encryption key for the clothes washer.

The stream is not encrypted using OpenSSL `SSL_Write()`, so it doesn't show up in the trace logs.  I'll need to poke at the `libHCPService.so` to see if I can figure out what functions are used to transform the data. I see some that look promising like `websocketpp::connection<websocketpp::config::asio_tls_client>`, although I won't have time this morning to trace it.

**Comment by CRTified** [comment]
Thanks for confirming that it's not "trivially decodable" plain text. I'm not that well-versed with reversing, but feel free to ping me when I can help or test something.

**Comment by osresearch** [comment]
I've determined that the device configuration passed to `initHomeAppliance()` has an AES key and IV at the end of it for my clothes washer.  The `change_aes_data()` function takes two string arguments, one of which is a 256-bit base64 encoded key and the other is a 128-bit base64 encoded IV.

However, trying to use these with `openssl enc -d` has not proven to be successful yet.  I'm not sure of the cipher mode, and what seems likely to be the expanded AES key passed to `hcp::EncryptionHandlerImpl::rijndaelDecrypt()` does not match what I would expect it to look like for the key derived from the base64 value.

**Comment by osresearch** [comment]
It also appears that the messages are passed through hmac_sha256(), so there is a shared secret of some sort of it.

**Comment by osresearch** [comment]
Ah! The `change_aes_data()` input is not used as a key, but as a key-derivation-key. It is HMAC'ed with `ENC` to generate an encryption key and `MAC` to generate a validation key.  So I can now decode the message from the clothes washer, with an error, and without validation yet

Turn the base64 PSK into a hex key:
```
% echo 'KlRQQyG8AkEfRFPr0v7vultz96zcal5lxj2fAc2ohaY"' | base64 -d | xxd -g1
00000000: 2a 54 50 43 21 bc 02 41 1f 44 53 eb d2 fe ef ba  *TPC!..A.DS.....
00000010: 5b 73 f7 ac dc 6a 5e 65 c6 3d 9f 01 cd a8 85 a6  [s...j^e.=......
```

Derive the encryption key from the PSK:
```
% echo -n ENC | openssl dgst -sha256 -mac hmac -macopt hexkey:2A54504321BC02411F4453EBD2FEEFBA5B73F7ACDC6A5E65C63D9F01CDA885A6 -binary | xxd -g1
00000000: 1d 73 0a 77 e6 22 da 4d 61 4b 48 bc 3e 3e 87 e4  .s.w.".MaKH.>>..
00000010: c6 d6 c6 b1 74 ac 87 b3 5d e0 3f 37 85 4c 80 b9  ....t...].?7.L..
```

Capture the server hello on the HTTP websocket:
```
% cat wstest 
#!/usr/bin/env python3
import websocket
import sys
sys.stdout.buffer.write(
  websocket.create_connection("ws://10.1.0.145/homeconnect")
  .recv()
)
```

And decode it with the derived key:
```
%  ./wstest | openssl enc -aes256  -nosalt -d  \
  -K  1d730a77e622da4d614b48bc3e3e87e4c6d6c6b174ac87b35de03f37854c80b9 \
  -iv b5352fa9cb0195db64847bc3c04d83a5 \
< ws-clothes.enc  | xxd -g1
bad decrypt
140684300555584:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../crypto/evp/evp_enc.c:610:
00000000: 7b 22 73 49 44 22 3a 31 36 39 35 32 38 31 38 39  {"sID":169528189
00000010: 31 2c 22 6d 73 67 49 44 22 3a 31 33 38 37 36 38  1,"msgID":138768
00000020: 38 39 38 32 2c 22 72 65 73 6f 75 72 63 65 22 3a  8982,"resource":
00000030: 22 2f 65 69 2f 69 6e 69 74 69 61 6c 56 61 6c 75  "/ei/initialValu
00000040: 65 73 22 2c 22 76 65 72 73 69 6f 6e 22 3a 32 2c  es","version":2,
00000050: 22 61 63 74 69 6f 6e 22 3a 22 50 4f 53 54 22 2c  "action":"POST",
00000060: 22 64 61 74 61 22 3a 5b 7b 22 65 64 4d 73 67 49  "data":[{"edMsgI
00000070: 44 22 3a 34 30 36 30 34 30 35 39 37 30 7d 5d 7d  D":4060405970}]}
00000080: 00 ee 94 b4 d1 f7 20 b9 c2 34 d6 cd 95 91 99 10  ...... ..4......
```

**Comment by CRTified** [comment]
Thank you. I'll try to extract the PSK tomorrow (UTC+1 here) and see whether this applies to the coffee maker.

**Comment by osresearch** [comment]
I just added something to the readme for (maybe) easier machine description and configuration retrieval. This will dump the arguments to `initHomeAppliance()`, which will contain a byte array of protobuf (I think) with the xml files, config, network, and psk:

```
frida-trace -o initHomeAppliance.log -f "com.bshg.homeconnect.android.release" -U -j '*!initHomeAppliance''
```

**Comment by osresearch** [comment]
The reason for the decrypt error is padding related.  Adding `-nopad` to the command cleans that up:
```
cat ws-clothes.enc | openssl enc -aes256 -nopad -nosalt -d    -K  1d730a77e622da4d614b48bc3e3e87e4c6d6c6b174ac87b35de03f37854c80b9   -iv b5352fa9cb0195db64847bc3c04d83a5 | xxd -g1
00000000: 7b 22 73 49 44 22 3a 33 38 34 36 32 39 37 37 34  {"sID":384629774
00000010: 30 2c 22 6d 73 67 49 44 22 3a 31 30 32 36 34 35  0,"msgID":102645
00000020: 37 30 34 38 2c 22 72 65 73 6f 75 72 63 65 22 3a  7048,"resource":
00000030: 22 2f 65 69 2f 69 6e 69 74 69 61 6c 56 61 6c 75  "/ei/initialValu
00000040: 65 73 22 2c 22 76 65 72 73 69 6f 6e 22 3a 32 2c  es","version":2,
00000050: 22 61 63 74 69 6f 6e 22 3a 22 50 4f 53 54 22 2c  "action":"POST",
00000060: 22 64 61 74 61 22 3a 5b 7b 22 65 64 4d 73 67 49  "data":[{"edMsgI
00000070: 44 22 3a 32 37 35 38 30 36 36 36 31 35 7d 5d 7d  D":2758066615}]}
00000080: 00 39 cb 7b c4 ba 0f 6b a5 fb 3c 36 cc 28 8b 10  .9.{...k..<6.(..
00000090: 9e a3 0d 00 fb 8f 3f eb 9f 7a 7b ed 7a 86 7e 9d  ......?..z{.z.~.
```

We should be able to validate the message using the KDF derived HMAC secret:

```
% echo -n MAC | openssl dgst -sha256 -hex -mac hmac -macopt hexkey:2A54504321BC02411F4453EBD2FEEFBA5B73F7ACDC6A5E65C63D9F01CDA885A6
(stdin)= d0b9c5991bb7941d370ee6fff1261c85cb555462ef2110f7dd637664f28f158b
```

I'm not at my desktop, so I can't trace the code.... Attempting to match up with the message in a TLS style "HMAC the cleartext, append it to the message, and then encrypt the whole thing" doesn't match:

```
% cat ws-clothes.enc \
| openssl enc -aes-256-cbc -nopad -nosalt -d    -K  1d730a77e622da4d614b48bc3e3e87e4c6d6c6b174ac87b35de03f37854c80b9   -iv b5352fa9cb0195db64847bc3c04d83a5 \
| head -c $[0x80] \
| openssl dgst -sha256 -mac hmac -macopt hexkey:d0b9c5991bb7941d370ee6fff1261c85cb555462ef2110f7dd637664f28f158b 
00000000: 23 b4 29 d7 47 5c ef 66 41 63 a3 d0 b8 c2 61 1d  #.).G\.fAc....a.
00000010: 71 15 25 e2 2a 2d eb 96 1d bf 33 f5 b8 62 28 6e  q.%.*-....3..b(n
```

HMAC'ing the ciphertext doesn't match up, either:

```
% xxd -g1 ws-clothes.enc  | tail -2
00000080: 20 cb 3b 08 a3 c4 82 90 37 fd a4 02 0c 8e 29 e9   .;.....7.....).
00000090: 19 8c 50 bb 88 f6 2b 1a f2 9e 7d 84 b0 82 1a bf  ..P...+...}.....

% head -c $[0x80] ws-clothes.enc | openssl dgst -sha256 -mac hmac -macopt hexkey:d0b9c5991bb7941d370ee6fff1261c85cb555462ef2110f7dd637664f28f158b -binary | xxd -g1
00000000: e6 95 a9 92 ef 63 5f e2 06 c0 5c dd 88 35 58 ad  .....c_...\..5X.
00000010: 89 c4 20 1a d1 7f c2 f7 b8 83 c8 63 c1 eb 5d d0  .. ........c..].
```

I'll need to add some trace points and test on the phone to figure out what's going on with the MAC and to validate that I hvae the correct key.

**Comment by osresearch** [comment]
Validating *their* HMAC works in the python script when talking to the http websocket, although they are closing the connection on it when the script tries to reply.

```
from Crypto.Cipher import AES
from Crypto.Hash import HMAC, SHA256
from Crypto.Random import get_random_bytes

psk64 = 'KlRQQyG8AkEfRFPr0v7vultz96zcal5lxj2fAc2ohaY'
iv64 = 'tTUvqcsBldtkhHvDwE2DpQ'

psk = base64url(psk64 + '===')
iv = base64url(iv64 + '===')

def hmac(key,msg):
        return HMAC.new(key, msg=msg, digestmod=SHA256).digest()

enckey = hmac(psk, b'ENC')
mackey = hmac(psk, b'MAC')
last_rx_hmac = bytes(16)
last_tx_hmac = bytes(16)

def hc_decrypt(buf):
        global last_rx_hmac

        if len(buf) < 32:
                print("Short message?", buf.hex(), file=sys.stderr)
                return None
        if len(buf) % 16 != 0:
                print("Unaligned message? probably bad", buf.hex(), file=sys.stderr)

        # validate the message using the first 16-bytes of the HMAC
        their_hmac = buf[-16:]
        enc_msg = buf[0:-16]
        hmac_msg = iv + b'\x43' + last_rx_hmac + enc_msg
        our_hmac = hmac(mackey, hmac_msg)[0:16]

        if their_hmac != our_hmac:
                print("HMAC failure", their_hmac.hex(), our_hmac.hex(), file=sys.stderr)
                return None
        last_rx_hmac = their_hmac

        # finally decrypt the validated message
        msg = AES.new(enckey, AES.MODE_CBC, iv).decrypt(enc_msg)

        # trim the mandatory padding off the end
        pad_len = msg[-1]
        if len(msg) < pad_len:
                print("padding error?", msg.hex())
                return None

        return msg[0:-pad_len]
```

**Comment by osresearch** [comment]
I'm not sure what it doesn't like about my reply. Just to test it out, I'm replaying the same device id and stuff.

They send:
```
Encrypt 0x6eca8469a0 0x6eec9fab58 0x1
{"sID":1151472126,"msgID":60156642,"resource":"/ei/initialValues","version":2,"action":"RESPONSE","data":[{"deviceType":"Application","deviceName":"Pixel","deviceID":"d304ee06571f0d09"}]}
HMAC 0x20 0xe1
           0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F  0123456789ABCDEF
00000000  d0 b9 c5 99 1b b7 94 1d 37 0e e6 ff f1 26 1c 85  ........7....&..
00000010  cb 55 54 62 ef 21 10 f7 dd 63 76 64 f2 8f 15 8b  .UTb.!...cvd....
           0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F  0123456789ABCDEF
00000000  b5 35 2f a9 cb 01 95 db 64 84 7b c3 c0 4d 83 a5  .5/.....d.{..M..
00000010  45 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  E...............
00000020  00 fa 81 28 71 05 1e 90 fd 47 59 6d 50 97 8e 6e  ...(q....GYmP..n
00000030  63 1d 38 8e ec 58 fd 40 a6 9d b4 fb 57 37 bf cd  c.8..X.@....W7..
00000040  7d c8 95 47 7d f2 f9 9e e8 be 54 8f b7 1d 0f a4  }..G}.....T.....
00000050  c6 0a 1d 50 76 9a e8 a4 03 31 8b 0e 57 82 87 5d  ...Pv....1..W..]
00000060  89 48 a5 03 a0 d1 0b e3 cb 16 5a 10 cb 7f 8b 44  .H........Z....D
00000070  d2 1e 42 1f 59 35 53 61 c6 63 8b 66 8b 9d 9a 07  ..B.Y5Sa.c.f....
00000080  6b 46 cb a1 d8 3b ce 2d e0 a1 78 96 5e 41 0b fe  kF...;.-..x.^A..
00000090  e5 92 01 ac 16 1f 93 26 06 e7 70 91 f3 f8 af f2  .......&..p.....
000000a0  0f ce e7 4c f1 49 e2 f1 e6 74 f1 d9 90 a4 ed a5  ...L.I...t......
000000b0  fd 7a 66 b5 68 a8 a5 be f8 c9 82 18 d6 f4 8a 65  .zf.h..........e
000000c0  08 8e 52 e1 69 11 a5 b2 4c 22 d7 56 88 76 21 63  ..R.i...L".V.v!c
000000d0  a4 81 96 38 31 57 61 65 66 39 46 2d 42 36 4f a7  ...81Waef9F-B6O.
000000e0  a6                                               .
           0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F  0123456789ABCDEF
00000000  00 69 54 30 22 20 ff c9 66 79 f8 ee 6d b6 1a 41  .iT0" ..fy..m..A
00000010  51 1e 4a 8e 98 ea f0 cb 5a 45 a9 bf 9f 8a ee 1b  Q.J.....ZE......
```

which decodes correctly with the python and openssl tools.

Something incorrect in the previous example is that the CBC context is preserved between messages so that the last cipher block is mixed into the first block of the next message.

**Comment by osresearch** [comment]
Wait, their websocket is sending 0x82, "binary frame", while Python's websocket is sending 0x81, "text frame".  Changing it to `ws_send_binary()` instead and now it keeps talking!

```
./hcpy 
2022-02-03 19:20:36.218319 RX: {'sID': 1308648388, 'msgID': 266994003, 'resource': '/ei/initialValues', 'version': 2, 'action': 'POST', 'data': [{'edMsgID': 1786934035}]}
2022-02-03 19:20:36.218384 TX: {'sID': 1308648388, 'msgID': 266994003, 'resource': '/ei/initialValues', 'version': 2, 'action': 'RESPONSE', 'data': [{'deviceType': 'Application', 'deviceName': 'Pixel', 'deviceID': 'd304ee06571f0d09'}]}
2022-02-03 19:20:36.219345 TX: {'sID': 1308648388, 'msgID': 1786934035, 'resource': '/ci/services', 'version': 1, 'action': 'GET'}
2022-02-03 19:20:36.219539 TX: {'sID': 1308648388, 'msgID': 1786934036, 'resource': '/ci/services', 'version': 1, 'action': 'GET'}
2022-02-03 19:20:36.219688 TX: {'sID': 1308648388, 'msgID': 1786934037, 'resource': '/iz/info', 'version': 1, 'action': 'GET'}
2022-02-03 19:20:36.219819 TX: {'sID': 1308648388, 'msgID': 1786934038, 'resource': '/ei/deviceReady', 'version': 2, 'action': 'NOTIFY'}
2022-02-03 19:20:36.222462 RX: {'sID': 1308648388, 'msgID': 266994004, 'resource': '/ci/registeredDevices', 'version': 2, 'action': 'NOTIFY', 'data': [{'endDeviceID': 0, 'deviceType': 'Application', 'deviceName': 'Pixel 3', 'deviceID': 'ab1edf88cd3dc7e3', 'connected': False, 'protected': False}, {'endDeviceID': 1, 'deviceType': 'Application', 'deviceName': 'Adelaide', 'deviceID': 'a7bd891e8eecdc3efb7f49c5', 'connected': False, 'protected': False}, {'endDeviceID': 2, 'deviceType': 'Application', 'deviceName': 'Pixel', 'deviceID': 'd304ee06571f0d09', 'connected': True, 'protected': False}]}
2022-02-03 19:20:36.224337 RX: {'sID': 1308648388, 'msgID': 1786934035, 'resource': '/ci/services', 'version': 1, 'action': 'RESPONSE', 'data': [{'service': 'ro', 'version': 1}, {'service': 'ei', 'version': 2}, {'service': 'ci', 'version': 2}, {'service': 'ni', 'version': 1}]}
2022-02-03 19:20:36.226325 RX: {'sID': 1308648388, 'msgID': 1786934036, 'resource': '/ci/services', 'version': 1, 'action': 'RESPONSE', 'data': [{'service': 'ro', 'version': 1}, {'service': 'ei', 'version': 2}, {'service': 'ci', 'version': 2}, {'service': 'ni', 'version': 1}]}
2022-02-03 19:20:36.227197 RX: {'sID': 1308648388, 'msgID': 1786934037, 'resource': '/iz/info', 'version': 1, 'action': 'RESPONSE', 'code': 404}
```

**Comment by osresearch** [comment]
Documentation has been updated!  Thanks again for pushing me to actually check out the HTTP port.  Let me know if you find anything interesting in the coffee maker!

**Comment by osresearch** [comment]
@CRTified Hopefully with the recent changes you can retrieve the PSK/AES/IV and device descriptions directly from the home connect servers using `hc-login $USERNAME $PASSWORD`.  Please let me know if it works for you!
